name: ektg
version: '3.7'

services:
  db:
    container_name: dbektg
    build:
      context: ./database/init
      dockerfile: Dockerfile
    command: postgres -c 'max_connections=2000'
    volumes:
      - ./database/data:/var/lib/postgresql/data
      #- ./database/init/tests.sql:/docker-entrypoint-initdb.d/tests.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ekspg
      POSTGRES_USER: eku01
      POSTGRES_PASSWORD: tnG4-gr6D
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eku01 -d ekspg | grep -w 'accepting connections' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ./..
      dockerfile: ./scripts/app/Dockerfile
    container_name: app-ektg-container
    ports:
      - "8102:8102"
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  custom_network:
    driver: bridge