server:
  port: 8088

spring:
  application:
    name: ektg2

  jpa:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  #     ddl-auto: update # or create
  #     format_sql: true
  #   show-sql: true

  datasource:
    url: jdbc:postgresql://dbektg:5432/ekspg
    username: eku01
    password: tnG4-gr6D
    driver-class-name: org.postgresql.Driver

  # liquibase:
  #   enabled: false
  #   driver: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/ekspg
    # username: eku01
    # password: tnG4-gr6D
    # driver-class-name: org.postgresql.Driver
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yaml
    enabled: true    

# # actuator
# management:
#   info:
#     env:
#       enabled: true
#   endpoint:
#     health:
#       show-details: always
#   endpoints:
#     web:
#       exposure:
#         include: info,health,prometheus

info:
  app:
    name: Secondhand service
    version: 1.0.0
    description: Сервис барахолка